# Generated by Django 3.2.25 on 2024-04-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripinspiration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='formattedlink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
