# Generated by Django 3.2.25 on 2024-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripinspiration', '0002_alter_activity_formattedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
